title: My Dashboard
header_style: black on blue
live_duration: 1000
layout:
- size: 10
  subprocess:
  - command: ss -s
    refresh: 2
    title: "\U0001F9A9  ss"
  - command: ping -c 1 1.1
    refresh: 0.2
    title: "\U0001F980  ping"
    border_style: bright_blue
- size: 5
  subprocess:
  - command: vmstat -S M
    title: "\U0001F422  vmstat"
- size: 3
  subprocess:
  - command: uptime
    title: "\U0001F408  uptime"
- size: 3
  subprocess:
  - command: notfound
    title: "\U0001F408  notfound"
