layout:
- name: ss_ping
  size: 10
  split_row:
  - command: ss -s
    name: ss
    refresh: 1
    title: "\U0001F9A9  ss"
  - command: ping -c 1 1.1
    name: ping
    refresh: 0.6
    title: "\U0001F980  ping"
- command: vmstat -S M
  name: vmstat
  refresh: 1
  size: 5
  title: "\U0001F422  vmstat"
- command: uptime
  name: uptime
  refresh: 1
  size: 3
  title: "\U0001F408  uptime"
- command: notfound
  name: notfound
  refresh: 1
  size: 3
  title: "\U0001F408  notfound"
