[tool.poetry]
name = "dboard"
version = "0.1.0"
description = ""
authors = ["Marcelo Félix"]

[tool.poetry.dependencies]
python = "^3.11.2"
rich = "^13.3.2"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
